### ISSUE TITLE
Release version 0.6.0

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1032]
Following up on the discussion in #895, it'd be good to release version 0.6.0 in March or April.  We can use this issue to discuss what we want to make sure gets into this release.

**Comment by namurphy** [comment]
There are a few things related to `plasmapy.particles` that I think we ought to get into our next release.  

 - [ ] We updated `ParticleLike` in #985 to include a (hopefully) complete description of how particles can be represented in PlasmaPy.  We ought to use `ParticleLike` in docstrings consistently in the formulary and elsewhere to link to that description, especially since particles can be confusing when beginning to use PlasmaPy.  
 - [ ] If we want to use `ParticleLike` in type hint annotations, we would need to update `@particle_input` to accept `ParticleLike` instead of (or in addition to) `Particle`.  Related to: #912, #913.  
 - [ ] Similarly, we should make `@particle_input` accept `CustomParticle` instances (#807).
 - [ ] I'd like to get `ParticleList` (#948, #1017) implemented, and make it such that `plasmapy.formulary` functions can work with lists of particles (i.e., `gyroradius(B=..., particle=["p+", "e-"])` would return an array with the gyroradii for protons and electrons).  This would also require some changes to `@particle_input` too.

**Comment by StanczakDominik** [comment]
Oh wow, you mean you read what's going on in those big PRs? I have to admit I've stopped doing that for PRs I'm not handling, and wanted to discuss this at the telecon today :D but sure...

I'll review the particle list asap!

**Comment by StanczakDominik** [comment]
You know what we should also do?

- [ ] Change the three featured notebooks on the main docs index to showcase the newest and coolest functionality

**Comment by namurphy** [comment]
> Change the three featured notebooks on the main docs index to showcase the newest and coolest functionality

Perhaps we could have the first notebook be one for getting started with PlasmaPy, and the other two could be the newest and coolest functionality?

**Comment by StanczakDominik** [comment]
Quoting myself from chat:

> Honestly I dislike the ITER data analysis notebook, it's too basic; can we just replace that with the proton radiography one and keep thomson up? Make this an actual highlight reel and I promise I'll write a proper "start using plasmapy" notebook for 0.7?

This is what pushed through #1065 and what I commit to doing for 0.7. For now, we're on schedule to release tomorrow, so I'll close this one :)
