### ISSUE TITLE
[EPIC] Add Thomson Fitting

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1182]
This issue outlines what needs to be done to get Thomson fitting added to PlasmaPy (in order)

- [x] Create lite-function framework
    - [x] Functionality side for framework (PR #1145)
    - [ ] Documentation side of framework (**PR yet to be opened**)

- [x] Add required lite-functions
    - [x] Apply framework for `plasmapy.formulary.parameters.thermal_speed`
        (PR #1145)
    - [x] Apply framework for `plasmapy.formulary.parameters.plasma_frequency`
        (PR #1308)
    - [x] Apply framework for `plasmapy.dispersion.dispersionfunction`
        (PR #1473)
    - [x] Apply framework for `plasmapy.formulary.dielectric.permittivity_1D_Maxwellian`
        (PR #1476 )

- [x] Add Thomson fitting functionality
      (PR #974)
- [x] Add Thomson fitting notebook
    (PR #1520)

**Comment by pheuer** [comment]
Not sure why this is still open - we've had Thomson fitting working for a while now! Go us!
