### ISSUE TITLE
[EPIC] The new normalizations

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1319]
One of the next steps for expanding `plasmapy.simulation` will be creating classes to represent normalizations for different systems of equations, in particular those that represent plasmas.  This will include the overarching functionality needed for all of these classes, as well as the more specific functionality for concrete classes. 

***Issues and pull requests***

 - [ ] #808 Create classes to represent normalizations in simulation subpackage
 - [ ] #1029 Create class to represent MHD normalizations

**Issues to create** [WIP]
 - [ ] Create a standard way to store normalization values 
 - [ ] Create a standard way to store (calculate?) normalization relationships
 - [ ] Add to the base class a method like `_get_normalization_from_physical_type` which will accept a `u.PhysicalType` instance and give a normalization value
 - [ ] Create class to represent Vlasov-Maxwell normalizations (as used by Gkeyll)
 - [ ] Start a page on normalizations in the narrative documentation (including a description of how to normalize equations with an example, such as for MHD)
 - [ ] Define (and derive?) each normalization in the narrative documentation

** Tasks
 - [ ] Read up on SymPy and figure out if it would be helpful with the algebra stuff
 - [ ] Need to figure out the implementation strategy
