### ISSUE TITLE
[EPIC] Swept Langmuir Overhaul

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1402]
The issues outlines and summarizes the work being done on the swept Langmuir overhaul.  This overhaul will happen in several phase: Phase 1 will be the development of tools in `plasmapy.analysis` and Phase 2 will be the incorporation of the `plasmapy.analysis` tools into an `xarray` framework replacing functionality in `plasmapy.diagnostics`.

GitHub Project: https://github.com/PlasmaPy/PlasmaPy/projects/19 (not well maintained)

## Functionality:

- [x] Create `plasmapy.analysis.swept_langmuir`
    * PR #889
- [x] Floating potential
    * PR #889
    * `plasmapy.analysis.swept_langmuir.find_floating_potential`
    * Via `I = 0` crossing point
- [ ] Ion-Saturation Current (`Isat`)
    * PR #1469 
    * `plasmapy.analysis.swept_langmuir.find_ion_saturation_current`
    * curve fit ion-saturation region of the I-V curve
- [ ] Plasma Potential via `dI/dV`
    * PR #897
    * `plasmapy.analysis.swept_langmuir.find_plasma_potential_didv`
    * Estimates the floating potential from the peak of the first-derivative of the I-V curve (i.e. dI/dV)
- [ ] Electron Temperature from left side fit of `dI/dV`
- [ ] Electron Temperature from linear fit of `log(I)` vs `V`

## Notebooks

- [x] [`find_floating_potential`](https://docs.plasmapy.org/en/latest/notebooks/analysis/swept_langmuir/find_floating_potential.html)
    * PR #889
- [ ] `find_ion_saturation_current`
- [ ] `find_plasma_potential_didv`
