### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#566]
Our version 0.1.0 release was in April 2018, so we should plan on releasing version 0.2.0 soon.  Version 0.2.0 will be a development release.  We should not try to be feature complete, and users should expect that the API will be unstable for all subpackages (or at best, metastable).  

We should decide which features and functionality to prioritize for version 0.2.0.  At the same time, we should be realistic about how much time each of us has to contribute to a release since none of us are doing this full time.  The issues that we are not going to prioritize should be changed to version 0.3.0.  

Let's use this as a meta-issue to keep track of all of the other issues and make decisions about what to prioritize.

Thanks!
Nick

**Comment by namurphy** [comment]
The highest priority for me is to make improvements to the `transport` subpackage, without adding functionality.

 - [ ] Write docstrings for every public-facing function, class, or method in `transport` (#308, #310, etc.)
 - [ ] Improve narrative documentation for `transport` (#416)
 - [ ] Refactor `transport` subpackage (#248, #307, #309, #387, etc.)

I'm currently working on classes to represent ionization states, and my goal is to implement the non-equilibrium ionization functionality that we've worked on in a separate project. 

 - [ ] Create classes to represent ionization states (#352 , #404) 
 - [ ] Calculate collisional ionization equilibrium and non-equilibrium ionization (#521)

Some other issues that are higher on my priority list are:

 - [ ] Remove implicit default particle assumptions (#453)
 - [ ] Implement @particle_input and Particle class in physics subpackage (#341)
 - [ ]  Clarify docstring style guidelines in development guide (#273) 
 - [ ]  Clarify code style guidelines in development guide (#274)
 - [ ]  Create Plasma subclass for plasma described analytically in Cartesian coordinates with fluid approximation (#565)

**Comment by StanczakDominik** [comment]
Mostly done! Leftovers: 

- [ ] Make the release on conda-forge
- [ ] Mint a release on Zenodo and get a digital object identifier (DOI)
- [ ] Notify plasma physics communities about the release
- [ ] Post release announcement on social media sites
- [ ] Send release announcement to mailing list
- [ ] Update CHANGELOG.rst (Add a new heading for the next release)

**Comment by StanczakDominik** [comment]
Waiting on #93 which in turn is waiting on https://github.com/conda-forge/staged-recipes/pull/6694
