### ISSUE TITLE
Release version 0.4.0

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#795]
This is a meta-issue to discuss our 0.4.0 release, which is due in the spring of 2020.  Some of the existing pull requests that (in my opinion) should be prioritized include:

 - [ ] Particle tracker PR (#675)
 - [ ] Refactoring of test helpers vis `plasmapy.tests.helpers` (#728)
 - [ ] Update getting started docs (#776)
 - [ ] Create `plasmapy.addons` (#783)
 - [ ] Consolidate requirements (#789)

For the new [PlasmaPy-NEI](https://github.com/PlasmaPy/PlasmaPy-NEI) affiliated package, it would be really helpful to get #783 in (so `plasmapy_nei` can actually be an addon) and also #728 since I'd like to use the refactored test runners to make some new tests over there.  We also renamed `plasmapy.atomic` into `plasmapy.particles` during [The Great Restructuring](https://github.com/PlasmaPy/PlasmaPy-PLEPs/pull/26).  

We should also do triage and update the `v0.4.0` milestone to figure out what issues should be prioritized.
