### ISSUE TITLE
Create aliases for common formulary functions.

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#856]
### Update (2020-12-17)

Most of the common `plasmapy.formulary` functionality has been given aliases.  This issue is being left open since aliases may be desired on future functionality.  If there's functionality that does not have an alias and you'd like one, then please leave a comment.

----

Explicit function names are great for readability and clarity, and the primary functions should remain like that.  However, explicit names can be long and become burdensome for users.  Users either work with the long names or have to individually import each function and rename it to a more manageable name.  Thus, I propose we make aliases for, at least, the most common formulary functionality.  Implementation would looks something like...

```python
__all__ = ["Alfven_speed", "va_"]

...

def Alfven_speed(...):
    ...
    return speed

va_ = Alfven_speed
"""Alias to :func:`Alfven_speed`."""

# or

#: Alias for :func:`Alfven_speed`.
va_ = Alfven_speed
```
### Development points

* Aliases will have a trailing underscore to signify they are aliases and allow users to still use the shortest abbreviations for their code. For example,

  ```python
  from plasmapy.formulary import va_

  va = va_(...)
  ```
* Aliases shout be documented in the docstring of the parent function after the main description but before the parameters list.

  ```python
  def Alfven_speed(...):
      """
      Main function description

      **Aliases:**  `va_`

      Parameters
      ----------
      ...
      """
  ```

* Aliases should be tested in the the parent function `pytest`s.  This can be done with the following simple `assert` statement.

  ```python
  assert va_ is Alfven_speed
  ```

### List of functions to make aliases for...

(By no means is this a complete list and will be updated as needed.)

- [x] `Alfven_speec` -> `va_` (PR #865)
- [x] `Bohm_diffusion` -> `DB_`  (PR #865)
- [x] `deBroglie_wavelength` -> `lambdaDB_` (PR #865)
- [x] `Debye_length` -> `lambdaD_` (PR #865)
- [x] `Debye_number` -> `nD_` (PR #865)
- [x] `ExB_drift` -> `veb_` (PR #865)
- [x] `Fermi_energy` -> `Ef_` (PR #865)
- [x] `force_drift` -> `vfd_` (PR #865)
- [x] `gyrofrequency` -> `oc_` `wc_` (PR #865)
- [x] `gyroradius` -> `rc_` `rhoc_` (PR #865)
- [x] `inertial_length` -> `cwp_` (PR #865)
- [x] `ion_sound_speed` -> `cs_` (PR #865)
- [x] `ionization_balance` -> `Z_bal_` (PR #860, #851)
- [x] `kappa_thermal_speed` -> `vth_kappa_` (PR #865)
- [x] `lower_hybrid_frequency` -> `wlh_` (PR #865)
- [x] `Mag_Reynolds` -> `Rm_` (PR #865)
- [x] `magnetic_energy_density` -> `ub_` (PR #865)
- [x] `magnetic_pressure` -> `pmag_` (PR #865)
- [x] `mass_density` -> `rho_` (PR #865)
- [x] `plasma_frequency` = `wp_` (PR #865)
- [x] `Reynolds_number` -> `Re_` (PR #865)
- [x] `thermal_deBroglie_wavelength` -> `lambdaDB_th_` (PR #865)
- [x] `thermal_speed` -> `vth_` (PR #865)
- [x] `thermal_pressure` -> `pth_` (PR #865)
- [x] `upper_hybrid_frequency` -> `wuh_` (PR #865)
- [ ] ...

**Comment by StanczakDominik** [comment]
I guess I'll close #855 as this is way more of a complete description.

**Comment by svincena** [comment]
I'm a little late on commenting on this, but was there a discussion about the capitalization of proper names in some aliases but not in others? Examples: Debye, Bohm, Reynolds (nD_, DB_, Re_), etcetera, but not Alfvén or Fermi (va_, Ef_).

**Comment by rocco8773** [comment]
@svincena There was no detained discussion about them.  For the most part, [PEP8 standards (all lowercase for functions)](https://www.python.org/dev/peps/pep-0008/#id45) were used unless the field's common convention used a capital.  For example, the Debye length is commonly written as a lambda with a subscript D, so the alias is `lambdaD_`.  While I personally don't like adding capital letters to functions, I think adhering to the field's convention improves readability/clarity.

With that said, we're open to suggestions because there's always room for improvement.

**Comment by svincena** [comment]
The common convention in published work is to use $v_{A}$, not $v_{a}$ as the Alfvén speed. I agree, it's easier to type va_, but I was just thinking of making things consistent. Ok, $v_{\mathrm {A}}$ if you're going to get really picky with how I wrote that.

**Comment by rocco8773** [comment]
Yeah, the Alfven speed is a tricky one.  I've seen people use `VA`, `vA`, and `va`, with (my small sample size) `VA` and `va` being the most common.  While `vA` better matches the field's standard convention, I felt that `va` was still recognizable enough that it was safe to go with PEP8 standards and ease of use (that's kind of the point of aliases).  I wasn't going to go with something like `v_A_` because it's less friendly to use and didn't add any additional clarity to the name.

With that said, I don't have an issue with creating a `vA_` alias but that would be in addition to `va_` and not replace `va_`.

**Comment by svincena** [comment]
Sounds good.

**Comment by StanczakDominik** [comment]
> Most of the common plasmapy.formulary functionality has been given aliases. This issue is being left open since aliases may be desired on future functionality. If there's functionality that does not have an alias and you'd like one, then please leave a comment.

Eh... this issue is 100% done atm, and I'd rather not leave it up "in case something comes up". If it's closed (as per the "100% done atm" criterion!), it's just as searchable as it is now :) So I'd rather close it for now.
