### ISSUE TITLE
Tasks to perform after the test helper refactoring is complete

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#930]
This issue is a place to keep track of tasks that should be done (or at least thought about) after the test helpers refactoring is complete.

 - [ ] Make sure that `plasmapy/tests/helpers/__init__.py` is organized nicely with comments removed (should be done in #929)
 - [ ] Update tests for `IonizationState` and `IonizationStateCollection` that I skipped in #796
 - [ ] Update usage of `call_string` elsewhere in the package, and begin applying the method and attribute equivalents of `call_string` where necessary
 - [ ] Remove `Error` from the names of test helper exceptions? (i.e. `ExceptionMismatchError` → `ExceptionMismatch`)
 - [ ] Create a new pull request for refactored tests in `test_atomic.py` that were already done in #728
 - [ ] Create issues on applying `test_runner` to tests in `plasmapy.particles` and `plasmapy.formulary`
 - [ ] Check if the rest of the testing guide in the development docs needs to be updated
 - [ ] Make the functionality in `plasmapy.tests.helpers` private except for `test_runner` and the test inputs classes that developers are supposed to be interfacing with?

The tasks listed in this issue and in comments below should be addressed after the following pull requests are merged: #919, #920, #921, #922, #923, #924, #925, #926, #927, #928, and/or #929.

**Comment by namurphy** [comment]
- [ ] Make sure that when the exceptions in `exceptions.py` are raised, they show up in the error message not showing their full path
