### ISSUE TITLE
Refactor collisions.py

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#931]
There are a couple of things we can do to refactor and refine [plasmapy.formulary.collisions](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/formulary/collisions.py) ([permalink](https://github.com/PlasmaPy/PlasmaPy/blob/6d5651cb9cfb7bd010c8e81c45a1bffeb9c4e95d/plasmapy/formulary/collisions.py)).  Some possibilities for changes include:

 - [ ] Choose a more descriptive name for `_boilerplate`
 - [ ] [Replace extended `if/`else` statements with polymorphism](https://www.codementor.io/@uditrastogi/replace-conditional-statements-if-else-or-switch-with-polymorphism-ryl8mx4ns)?
 - [ ] Figure out if [line 339 in `collisions.py`]() is reachable, as per [this discussion](https://github.com/PlasmaPy/PlasmaPy/pull/911#issuecomment-707761434) in #911.
 - [ ] Stop using `z_mean` in favor of `CustomParticle`, possibly in conjunction with `@particle_input` (see also #912, #918)
 - [ ] Choose more descriptive names than `GMS-1`, etc. for Coulomb logarithms
 - [ ] Improve RestructuredText formatting in docstrings (i.e. putting back ticks around variables, etc.)
 - [ ] Use PEP 8 naming standards for variables

I'm also wondering if we should have something like an `AbstractInteraction` base class, and then have different classes to represent the different types of collisions and reactions...like `ChargeExchangeCollision` or `ElectronImpactIonization` or `NuclearReaction`.  Then there could be attributes like `cross_section`, `reaction_rate`, `reduced_mass`, etc.

**Comment by arichar6** [comment]
👍 from me for replacing if/else conditionals with polymorphism! It makes code easier to read, easier to maintain, and more flexible.

**Comment by rocco8773** [comment]
>     * Figure out if line 339 in `collisions.py` is reachable, as per [this discussion](https://github.com/PlasmaPy/PlasmaPy/pull/911#issuecomment-707761434) in #911.

This was fixed with https://github.com/PlasmaPy/PlasmaPy/pull/911#discussion_r504210317.

**Comment by Tiger-Du** [comment]
For Coulomb logarithms, perhaps a more descriptive naming scheme is 1: `classical` or `LS`, 2: `LS_min_interp` or `LS_clamp`, 3: `LS_full_interp`, 4: `hyp_LS`, 5: `hyp_LS_max_interp`, and 6: `hyp_LS_full_interp`, or something similar to this. `_interp` could be abbreviated to `I`, and `hyp_` could be abbreviated to `H`.

**Comment by lemmatum** [comment]
For the long if/else statements, some of those are trying to handle different input types, and in those cases [multiple dispatch](https://multiple-dispatch.readthedocs.io/en/latest/design.html) might be useful. I also :heart:  polymorphism.

**Comment by namurphy** [comment]
- [ ] In several of these functions `z_mean` is decorated with `u.dimensionless_unscaled` when it shouldn't need to be a `Quantity`.  Whilst reviewing #1229 it appeared that providing a float led to an unnecessary warning, which we should look into and fix.

**Comment by rocco8773** [comment]
#1769 is refactoring `collisions.py` into a `collisions` subpackage.  This should allow for easier maintainability and expandability.

**Comment by rocco8773** [comment]
#1747 outlines some expansion functionality for collisions.
